export const GET_TOURNAMENTS_START: string = 'GET_TOURNAMENTS_START';
export const GET_TOURNAMENTS_SUCCESS: string = 'GET_TOURNAMENTS_SUCCESS';
export const GET_TOURNAMENTS_FAIL: string = 'GET_TOURNAMENTS_FAIL';
export const GET_TOURNAMENTS: string = 'GET_TOURNAMENTS';
export const DELETE_TOURNAMENTS_SUCCESS: string = 'DELETE_TOURNAMENTS_SUCCESS';
export const CREATE_TOURNAMENT_SUCCESS: string = 'CREATE_TOURNAMENT_SUCCESS';
export const EDIT_TOURNAMENT_SUCCESS: string = 'EDIT_TOURNAMENT_SUCCESS';
export const DELETE_TOURNAMENT_SUCCESS: string = 'DELETE_TOURNAMENT_SUCCESS';
